server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        # User service
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        # Transaction service
        - id: transaction-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/transactions/**

        # Reward service
        - id: reward-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/rewards/**

        # Notification service
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/notifications/**

#jwt:
#  secret: my-super-secret-key-that-you-never-share
#  expiration: 86400000

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.server: DEBUG

